/**
 * Client-side voice contract. Mirrors docs/08 §2 (VoiceEngine and its events),
 * docs/09 §5 and §8 (evidence envelope, dataset brief) and docs/10 §3, §4, §6
 * (context envelope, canonical state, AffectEstimate, StyleDecision).
 *
 * Contract version: 2026-10-09.2 (optional cloned voice, docs/08 §15; additive
 * over `.1`). A change here is a contract change (R-30): update the doc first.
 */

export const CONTRACT_VERSION = "2026-10-09.2";

// ── Engine ───────────────────────────────────────────────────────────────────

export type EngineId = "openai" | "gemini";

/** Who produces the agent's audio: the engine's own voice or the cloned one (docs/08 §15). */
export type VoiceMode = "engine" | "cloned";

export type EngineStatus =
  | "idle"
  | "connecting"
  | "listening"
  | "thinking"
  | "speaking"
  | "renewing"
  | "error";

export interface VoiceEngine {
  readonly id: EngineId;
  connect(opts: { conversationId: string; seed?: ContextEnvelope; style?: StyleDecision; voiceMode?: VoiceMode }): Promise<void>;
  disconnect(reason?: string): Promise<void>;
  /** Text mode (F-12). */
  sendText(text: string): void;
  /** User speech detected or the Stop button. The text is only given with the cloned voice (§15.4). */
  interrupt(playedMs: number, deliveredText?: string): void;
  /** Takes effect from the next turn. */
  applyStyle(style: StyleDecision): void;
  /** After renewing the session or switching engines. */
  seed(context: ContextEnvelope): void;
  on<K extends keyof EngineEvents>(e: K, cb: (ev: EngineEvent<K>) => void): () => void;
  /** Opens or closes the microphone mid-session, after the explicit voice consent (R-26). Optional. */
  setMicEnabled?(on: boolean): Promise<void>;
  /** Hands the engine a system note as a user turn so it answers it aloud (self-correction). Optional. */
  sendSystemNote?(text: string): void;
}

// ── Event envelope ───────────────────────────────────────────────────────────

export interface EngineEvent<K extends keyof EngineEvents = keyof EngineEvents> {
  schema_version: "1";
  /** UUID; stable if the event is re-sent. */
  event_id: string;
  /** Monotonic per session. */
  seq: number;
  /** Generated by the client on start. */
  conversation_id: string;
  turn_id: string | null;
  /** Canonical state version (docs/10 §4). */
  state_version: number;
  /** Agent response currently speaking. */
  generation_id: string | null;
  type: K;
  /** ms on the browser's monotonic clock since the session started. */
  t: number;
  payload: EngineEvents[K];
}

/** Distributive union: narrows `payload` when `type` is checked. */
export type AnyEngineEvent = { [K in keyof EngineEvents]: EngineEvent<K> }[keyof EngineEvents];

export interface EngineEvents {
  status: StatusPayload;
  transcript: TranscriptPayload;
  tool_call: ToolCallPayload;
  tool_result: ToolResultPayload;
  speech: SpeechPayload;
  interrupted: InterruptedPayload;
  latency: LatencyPayload;
  session: SessionPayload;
  error: ErrorPayload;
}

export interface StatusPayload {
  state: EngineStatus;
}

export type TranscriptRole = "user" | "agent";
export type TimeSource = "engine" | "local" | "arrival";

export interface TranscriptPayload {
  role: TranscriptRole;
  utterance_id: string;
  text: string;
  final: boolean;
  t_start: number;
  t_end: number;
  t_source: TimeSource;
  /** Experimental multi-voice refinement, e.g. "user:1" (docs/08 §8). */
  speaker?: string;
  /** utterance_id this one corrects; the original is preserved. */
  corrects?: string;
  /**
   * The partial bubble of this utterance turned out to be noise (an invented
   * transcript): remove it. Never final, so it is never analysed.
   */
  retracted?: boolean;
}

/** Tools the console knows by name. */
export type KnownToolName = "search_ips" | "get_ips_details" | "aggregate_ips" | "compare_ips" | "correct_context";
/**
 * Any tool the backend exposes. New tools (e.g. `verify_registration`, `area_profile`)
 * pass through the bridge and render generically; the `string & {}` keeps autocompletion.
 */
export type ToolName = KnownToolName | (string & {});

export interface ToolCallPayload {
  tool_call_id: string;
  name: ToolName;
  args: Record<string, unknown>;
}

export type ToolStatus = "ok" | "empty" | "ambiguous" | "unavailable" | "invalid";
export type CacheStatus = "live" | "fresh" | "stale";

export interface ToolTrace {
  soql: string;
  ms: number;
  rows: number;
  cache_status: CacheStatus;
}

export interface ToolResultPayload {
  tool_call_id: string;
  status: ToolStatus;
  trace: ToolTrace;
  /** Key of the evidence envelope kept by the UI (query_fingerprint). */
  evidence_ref: string;
}

export type SpeechKind = "ack" | "answer" | "brief";

export interface SpeechPayload {
  phase: "start" | "stop";
  generation_id: string;
  kind: SpeechKind;
  /** Absent means "engine". */
  voice?: VoiceMode;
}

export interface InterruptedPayload {
  generation_id: string;
  played_ms: number;
  /** Only the text aligned with audio that was actually played. */
  delivered_text: string;
  /** How `delivered_text` was obtained (docs/08 §2, contract `.2`; optional and additive). */
  delivered_basis?: "engine" | "word_timestamps" | "estimated";
}

export interface LatencyPayload {
  t_speech_end: number;
  t_ack_audio?: number;
  t_tool_start?: number;
  t_tool_end?: number;
  /** Cloned voice only: first answer text from the engine, first sentence sent to the synthesizer. */
  t_first_text?: number;
  t_tts_start?: number;
  t_first_useful_audio?: number;
  t_playback_stop?: number;
}

export interface SessionPayload {
  event: "renewed" | "switched" | "expiring" | "voice_changed";
  /** EngineId for `renewed`/`switched`; VoiceMode for `voice_changed`. */
  from?: EngineId | VoiceMode;
  to?: EngineId | VoiceMode;
  reason: string;
  attempt: number;
}

export type ErrorCode =
  | "MIC_DENIED"
  | "UNSUPPORTED_BROWSER"
  | "SESSION_EXPIRED"
  | "RATE_LIMITED"
  | "ENGINE_CONNECT_FAILED"
  | "ENGINE_DROPPED"
  | "ENGINE_QUOTA"
  | "TOOL_TIMEOUT"
  | "TOOL_INVALID"
  | "PLAYBACK_FAILED"
  | "SYNTH_UNAVAILABLE"
  | "SYNTH_CONNECT_FAILED"
  | "SYNTH_DROPPED"
  | "SYNTH_QUOTA"
  | "ANALYSIS_UNAVAILABLE";

export interface ErrorPayload {
  code: ErrorCode;
  message: string;
  retryable: boolean;
}

// ── Evidence envelope (docs/09 §5) ───────────────────────────────────────────

export type WarningCode =
  | "CUTOFF_2022"
  | "ROWS_ARE_CAPACITY_CATEGORIES"
  | "LEVEL_MISSING_MOSTLY"
  | "DISTRICT_AS_DEPARTMENT"
  | "MIXED_TYPES"
  | "SITE_CODES_NOT_PHYSICAL_SITES"
  | "NOT_AVAILABILITY"
  | "NULL_NOT_ZERO"
  | "PARTIAL_RESULT"
  | "STALE_CACHE"
  | "FILTER_NORMALIZED";

export interface GroupValue {
  key: string | null;
  value: number;
}

export interface Evidence {
  dataset_id: string;
  source_url: string;
  query_fingerprint: string;
  cutoff_raw: string;
  fetched_at: string;
  cache_status: CacheStatus;
  complete: boolean;
  unit: string;
  filters: Record<string, unknown>;
  warnings: WarningCode[];
}

export interface EvidenceEnvelope {
  schema_version: "1";
  tool_call_id: string;
  turn_id: string;
  state_version: number;
  status: ToolStatus;
  /** Tool-specific. `value` or `groups` for aggregates; kept open for the rest. */
  data: { value?: number; groups?: GroupValue[]; unit?: string; complete?: boolean; [k: string]: unknown } | null;
  evidence: Evidence;
  trace: { engine: string; soql: string; ms: number; rows: number };
  error: { code: string; message: string; retryable?: boolean } | null;
  next_cursor: string | null;
  /** Grounded compact text built by the backend for the voice engine (docs/09 §5). */
  for_model?: string;
  context_patch: Partial<CanonicalState> & Record<string, unknown>;
}

// ── Dataset brief (docs/09 §8) ───────────────────────────────────────────────

export interface DatasetBrief {
  title: string;
  source: { name: string; license: string; cutoff_raw: string; cutoff_date: string; url: string };
  stats: { rows: number; providers: number; site_codes: number; fetched_at: string; ms: number };
  limits: string[];
  suggested_questions: string[];
  spoken_brief: string;
  trace: { soql: string; ms: number; rows: number }[];
  /**
   * PROPOSED extension (not in docs/09 §8 yet): the brief already runs these two
   * queries, so exposing their results lets the cover page draw them. Optional.
   */
  by_nature?: GroupValue[];
  top_departments?: GroupValue[];
}

// ── Affect and style (docs/10 §6) ────────────────────────────────────────────

export type Sentiment = "positive" | "neutral" | "negative" | "uncertain";
export type Emotion = "alegría" | "tristeza" | "enojo" | "miedo" | "sorpresa" | "asco" | "neutral" | "incierta";
export type StateHint = "frustración" | "confusión" | "satisfacción" | "prisa" | "interés" | "desconocido";
export type AffectMethod = "text" | "voice" | "fused";

export interface AffectEstimate {
  turn_id: string;
  state_version: number;
  observed_at: string;
  sentiment: Sentiment;
  emotion: Emotion;
  state_hint: StateHint;
  method: AffectMethod;
  discrepancy: boolean;
  cues: string[];
  /** Optional and NOT calibrated: never rendered as a percentage. */
  confidence: number | null;
}

export type StyleId = "directo" | "calido" | "didactico" | "neutro";

export interface StyleDecision {
  style: StyleId;
  directives: string[];
  reason: string;
  source: "preference" | "inferred";
  applies_from_turn: number;
}

// ── Canonical state and context envelope (docs/10 §3–§4) ─────────────────────

export type TonePreference = "neutral" | "concise" | "warm";

export interface CanonicalState {
  conversation_id: string;
  turn_id: string | null;
  state_version: number;
  locale: "es-CO";
  transcript_original?: string;
  transcript_corrected?: string;
  intent?: string;
  confirmed_filters: Record<string, unknown>;
  pending_candidates: string[];
  missing_fields: string[];
  last_evidence_refs: string[];
  selected_site_keys: string[];
  summary: string;
  recent_turns: { role: TranscriptRole; text: string }[];
  tone_preference: TonePreference;
  recovery_count: number;
  engine_attempts: number;
  deadline_at?: number;
  generation_id?: string | null;
  cancelled?: boolean;
  delivered_text?: string;
}

/** Provider-neutral seed built when renewing a session or switching engines. */
export interface ContextEnvelope {
  instructions_version: string;
  state: Pick<
    CanonicalState,
    "conversation_id" | "state_version" | "confirmed_filters" | "selected_site_keys" | "pending_candidates" | "tone_preference"
  >;
  summary: string;
  /** Last 4 completed turns, heard text only. */
  recent_turns: { role: TranscriptRole; text: string }[];
  current_utterance?: { original: string; corrected?: string };
  /** Up to 5 compact tool results with their evidence ids and cutoff. */
  tool_results: { tool_call_id: string; name: ToolName; evidence_ref: string; cutoff: string; summary: string }[];
  allowed_tools: ToolName[];
}
